//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraPuntenWPFclient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WinkelServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AantalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrijsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Aantal {
            get {
                return this.AantalField;
            }
            set {
                if ((this.AantalField.Equals(value) != true)) {
                    this.AantalField = value;
                    this.RaisePropertyChanged("Aantal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prijs {
            get {
                return this.PrijsField;
            }
            set {
                if ((this.PrijsField.Equals(value) != true)) {
                    this.PrijsField = value;
                    this.RaisePropertyChanged("Prijs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWinkelService")]
    public interface IWinkelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/RegistreerKlant", ReplyAction="http://tempuri.org/IWinkelService/RegistreerKlantResponse")]
        bool RegistreerKlant(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/RegistreerKlant", ReplyAction="http://tempuri.org/IWinkelService/RegistreerKlantResponse")]
        System.Threading.Tasks.Task<bool> RegistreerKlantAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetWachtwoord", ReplyAction="http://tempuri.org/IWinkelService/GetWachtwoordResponse")]
        string GetWachtwoord(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetWachtwoord", ReplyAction="http://tempuri.org/IWinkelService/GetWachtwoordResponse")]
        System.Threading.Tasks.Task<string> GetWachtwoordAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Login", ReplyAction="http://tempuri.org/IWinkelService/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Login", ReplyAction="http://tempuri.org/IWinkelService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetKlantSaldo", ReplyAction="http://tempuri.org/IWinkelService/GetKlantSaldoResponse")]
        double GetKlantSaldo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetKlantSaldo", ReplyAction="http://tempuri.org/IWinkelService/GetKlantSaldoResponse")]
        System.Threading.Tasks.Task<double> GetKlantSaldoAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetProducts", ReplyAction="http://tempuri.org/IWinkelService/GetProductsResponse")]
        ExtraPuntenWPFclient.ServiceReference1.Product[] GetProducts(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/GetProducts", ReplyAction="http://tempuri.org/IWinkelService/GetProductsResponse")]
        System.Threading.Tasks.Task<ExtraPuntenWPFclient.ServiceReference1.Product[]> GetProductsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/BuyProduct", ReplyAction="http://tempuri.org/IWinkelService/BuyProductResponse")]
        bool BuyProduct(string username, string password, ExtraPuntenWPFclient.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/BuyProduct", ReplyAction="http://tempuri.org/IWinkelService/BuyProductResponse")]
        System.Threading.Tasks.Task<bool> BuyProductAsync(string username, string password, ExtraPuntenWPFclient.ServiceReference1.Product product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWinkelServiceChannel : ExtraPuntenWPFclient.ServiceReference1.IWinkelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WinkelServiceClient : System.ServiceModel.ClientBase<ExtraPuntenWPFclient.ServiceReference1.IWinkelService>, ExtraPuntenWPFclient.ServiceReference1.IWinkelService {
        
        public WinkelServiceClient() {
        }
        
        public WinkelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WinkelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinkelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinkelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistreerKlant(string username) {
            return base.Channel.RegistreerKlant(username);
        }
        
        public System.Threading.Tasks.Task<bool> RegistreerKlantAsync(string username) {
            return base.Channel.RegistreerKlantAsync(username);
        }
        
        public string GetWachtwoord(string username) {
            return base.Channel.GetWachtwoord(username);
        }
        
        public System.Threading.Tasks.Task<string> GetWachtwoordAsync(string username) {
            return base.Channel.GetWachtwoordAsync(username);
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public double GetKlantSaldo(string username, string password) {
            return base.Channel.GetKlantSaldo(username, password);
        }
        
        public System.Threading.Tasks.Task<double> GetKlantSaldoAsync(string username, string password) {
            return base.Channel.GetKlantSaldoAsync(username, password);
        }
        
        public ExtraPuntenWPFclient.ServiceReference1.Product[] GetProducts(string username, string password) {
            return base.Channel.GetProducts(username, password);
        }
        
        public System.Threading.Tasks.Task<ExtraPuntenWPFclient.ServiceReference1.Product[]> GetProductsAsync(string username, string password) {
            return base.Channel.GetProductsAsync(username, password);
        }
        
        public bool BuyProduct(string username, string password, ExtraPuntenWPFclient.ServiceReference1.Product product) {
            return base.Channel.BuyProduct(username, password, product);
        }
        
        public System.Threading.Tasks.Task<bool> BuyProductAsync(string username, string password, ExtraPuntenWPFclient.ServiceReference1.Product product) {
            return base.Channel.BuyProductAsync(username, password, product);
        }
    }
}
