//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AankoopRegel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AankoopRegel()
        {
            this.Hoeveelheid = 0;
        }
    
        public int Id { get; set; }
        public int Hoeveelheid { get; set; }
        public int ProductId { get; set; }
        public int AankoopId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Aankoop Aankoop { get; set; }
    }
}
