//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinkelModelContainer : DbContext
    {
        public WinkelModelContainer()
            : base("name=WinkelModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klant> Klanten { get; set; }
        public virtual DbSet<Product> Producten { get; set; }
        public virtual DbSet<Voorraad> Voorraden { get; set; }
        public virtual DbSet<Aankoop> Aankopen { get; set; }
        public virtual DbSet<AankoopRegel> AankoopRegels { get; set; }
    }
}
